# Generated by Django 2.2.4 on 2020-02-29 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mesaEntrada.models


class Migration(migrations.Migration):

    dependencies = [
        ('mesaEntrada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependenciasInternas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(help_text='Nombre de la dependencia a donse se entren los documentos', max_length=50, verbose_name='Nombre de la dependencia')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='unidades',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AddField(
            model_name='documento',
            name='Clasificacion',
            field=models.CharField(choices=[('PU', 'Público'), ('RE', 'Reservado'), ('CO', 'Confidencial'), ('SE', 'Secreto')], default='PU', max_length=2),
        ),
        migrations.AddField(
            model_name='documento',
            name='Documento_relacionado',
            field=models.ManyToManyField(blank=True, related_name='_documento_Documento_relacionado_+', to='mesaEntrada.documento', verbose_name='Documentos relacionados'),
        ),
        migrations.AddField(
            model_name='documento',
            name='Tramite',
            field=models.CharField(choices=[('RE', 'Recibido'), ('EM', 'Emitido')], default='RE', max_length=2),
        ),
        migrations.AddField(
            model_name='documento',
            name='nro_documento',
            field=models.CharField(help_text='Ingrese el Número del documento, recuerde que este valor es utilizado para las busquedas', max_length=50, null=True, verbose_name='Nro Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesaEntrada.estado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Fecha_entrada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Nro_sistema',
            field=models.CharField(default=mesaEntrada.models.crear_numero, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Obs',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Termino_interno',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesaEntrada.tipo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documento',
            name='asunto',
            field=models.TextField(help_text='Maximo de 200 caracteres', max_length=200),
        ),
        migrations.AlterField(
            model_name='documento',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesaEntrada.unidades', verbose_name='Origen/Destino'),
        ),
        migrations.AddField(
            model_name='documento',
            name='copia',
            field=models.ManyToManyField(blank=True, related_name='copia', to='mesaEntrada.dependenciasInternas', verbose_name='Copia:'),
        ),
        migrations.AddField(
            model_name='documento',
            name='entiende',
            field=models.ManyToManyField(related_name='entiende', to='mesaEntrada.dependenciasInternas', verbose_name='Entiende:'),
        ),
        migrations.AddField(
            model_name='documento',
            name='interviene',
            field=models.ManyToManyField(blank=True, related_name='interviene', to='mesaEntrada.dependenciasInternas', verbose_name='Interviene:'),
        ),
        migrations.AddField(
            model_name='documento',
            name='participa',
            field=models.ManyToManyField(blank=True, related_name='participa', to='mesaEntrada.dependenciasInternas', verbose_name='Participa:'),
        ),
        migrations.AddField(
            model_name='documento',
            name='pase',
            field=models.ManyToManyField(blank=True, related_name='pase', to='mesaEntrada.dependenciasInternas', verbose_name='Pase a:'),
        ),
    ]
