# Generated by Django 2.2.4 on 2020-02-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesaEntrada', '0002_auto_20200229_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='entiende',
            field=models.ManyToManyField(blank=True, related_name='entiende', to='mesaEntrada.dependenciasInternas', verbose_name='Entiende:'),
        ),
    ]
