# Generated by Django 2.2.4 on 2020-02-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesaEntrada', '0003_auto_20200229_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Termino_interno',
            field=models.DateField(blank=True, null=True),
        ),
    ]
