# Generated by Django 2.2.4 on 2020-02-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesaEntrada', '0004_auto_20200229_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
