# Generated by Django 2.2.4 on 2020-03-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesaEntrada', '0007_auto_20200302_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependenciasinternas',
            options={'verbose_name': 'Dependencia', 'verbose_name_plural': '3. Dependencias'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name_plural': '1. Registrar documentos'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': '4. Estados del documento'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': '5. Tipos de documentos'},
        ),
        migrations.AlterModelOptions(
            name='unidades',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': '2. Unidades'},
        ),
        migrations.AlterField(
            model_name='dependenciasinternas',
            name='dependencia',
            field=models.CharField(help_text='Nombre de la dependencia a donde se entregan los documentos', max_length=50, verbose_name='Nombre de la dependencia'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(help_text='Estado en que se encuentra el documento', max_length=50, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(help_text='Tipo de documento, Ej: Expediente, Memorándum, Gedo, etc.', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='unidad',
            field=models.CharField(help_text='Nombre de la Unidad de donde provienen o a donde se envían los documentos', max_length=50, verbose_name='Nombre de la Unidad'),
        ),
    ]
